### ISSUE TITLE
Set specific git clone commands for each branch

### ISSUE THREAD

**Issue by rpsene** [ocp-power-automation/ocp4-upi-powervs#183]
To avoid misunderstandings regarding using specific versions of this code, it would be good to add in the docs the following:

Clone the correct branch based on the OpenShift version you would like to install:

For OCP 4.6:

```
git clone --single-branch --branch release-4.6 https://github.com/ocp-power-automation/ocp4-upi-powervs.git
``` 

For OCP 4.5:

```
git clone --single-branch --branch release-4.5 https://github.com/ocp-power-automation/ocp4-upi-powervs.git
```

**Comment by bpradipt** [comment]
Fixed via https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/230
