### ISSUE TITLE
Verify whether or not IPs that belongs to the public network created by the automation are being used

### ISSUE THREAD

**Issue by rpsene** [ocp-power-automation/ocp4-upi-powervs#199]
Once the cluster is up and running it will be natural to expand the resources around it and eventually use the same pub network created to deploy the cluster for another VMs. For instance, I manually created a new NFS server in the pub network created by the TF automation. However, when deleting the cluster (specifically the network), it fails because of the IPs of that network is allocated. 

To ensure this error does not happen, we should verify during the deletion of the network if there is any port allocated to a VM which was not created by the automation and either leave the network there or ask about forcing the resources deleting completely. 

Error:

```
Error: {"description":"an error has occurred; please try again: unable to delete subnet for network 4f9be979-bafd-4478-bbfd-3023c9a43171 for cloud instance dad1780f13c54b8a9f7ea55778e965e0: Expected HTTP response code [] when accessing [DELETE https://192.168.24.136:9696/v2.0/subnets/87e3804c-301c-4b2e-8d69-0655a4d26d14], but got 409 instead\n{\"NeutronError\": {\"message\": \"Unable to complete operation on subnet 87e3804c-301c-4b2e-8d69-0655a4d26d14: One or more ports have an IP allocation from this subnet.\", \"type\": \"SubnetInUse\", \"detail\": \"\"}}","error":"internal server error"}
```

**Comment by yussufsh** [comment]
Whatever is created by Terraform will and should be deleted by Terraform. If you are doing any manual changes on the resources then it becomes your responsibility to either get it back to what Terraform state file has or remove the resource from the state file and then delete it manually later.

This is not a bug with the automation code. We cannot destroy the cluster leaving the public network alone, which is created by the automation. In fact there is no way to do so in TF lifecycle without user using `terraform state` commands to manually update the resources in state file.
