### ISSUE TITLE
terraform destroy error

### ISSUE THREAD

**Issue by lukebrowning** [ocp-power-automation/ocp4-upi-powervs#223]
module.nodes.null_resource.remove_worker[0] (remote-exec): pod/redhat-marketplace-4mf5r evicted
module.nodes.null_resource.remove_worker[0] (remote-exec): pod/prometheus-adapter-79bd7d5c9-ffzjn evicted
module.nodes.null_resource.remove_worker[0]: Still destroying... [id=7928149752953593866, 30s elapsed]
module.nodes.null_resource.remove_worker[1]: Still destroying... [id=4203784824677227330, 30s elapsed]
module.nodes.ibm_pi_instance.master[2]: Still destroying... [id=fac4755e-8aff-45f5-8d5c-1d3b58b7a229/c141c210-316f-4a76-9a5a-7f9a9ddf3e16, 30s elapsed]
module.nodes.null_resource.remove_worker[1] (remote-exec): There are pending pods in node "worker-1" when an error occurred: error when evicting pod "router-default-6d99c496cc-rl2n4": rpc error: code = Unavailable desc = transport is closing
module.nodes.null_resource.remove_worker[1] (remote-exec): pod/router-default-6d99c496cc-rl2n4
module.nodes.null_resource.remove_worker[1] (remote-exec): Following errors occurred while getting the list of pods to delete:
module.nodes.null_resource.remove_worker[1] (remote-exec): cannot delete rpc error: code = Unavailable desc = transport is closing: openshift-machine-config-operator/machine-config-daemon-lb9qmerror: unable to drain node "worker-1", aborting command...

module.nodes.null_resource.remove_worker[1] (remote-exec): There are pending nodes to be drained:

**Comment by lukebrowning** [comment]
@yussufsh Should there be a delay between the drain node and delete node in the underlying powervs code.  Or perhaps, a retry loop with a delay.

**Comment by yussufsh** [comment]
You can ignore this error during destroy. The problem is that master nodes also get destroy with the workers and the `oc` commands will always fail. Since we are creating masters and workers together in TF there is no way to delay worker removal before masters.

That said it is safe to ignore the errors and the code also wont fail on failures during removal of worker node.

**Comment by lukebrowning** [comment]
@yussufsh In my case, the worker nodes failed to be deleted.   The oc delete node command failed with an error message.   I forget the exact text of the message, but it was stating that there were active pods (osds, mon, ...) that could not be deleted.

In my case, OCS was configured, so there are more pods as well as persistent volumes allocated by CEPH transcending namespaces.   My question was whether the drain needed more time to complete as there was more work.   I think more investigation is needed here.   This [article](https://access.redhat.com/solutions/4289361) indicates that oc drain is not 100% and  there are ocp pod attributes to be considered.  

I have a work around here as I am preparing the worker nodes for deletion by invoking an application specific command, but it would be better if this was handled in ocp4-upi-powervs.    I am not sure if more time for drain would have done the job as application pods are terminated and release their hold on persistent volumes...

BTW, I did not see in the GUI how to re-open an issue.   Do you know?

**Comment by yussufsh** [comment]
Whatever was created by TF will be removed in the reverse order. So the bastion node will be the last node to be removed when you  run `terraform destroy` command. I am not sure what orphaned resources you are talking about? if you did any manual steps via UI then TF won't know it and won't delete it.

We have used drain only when we reduce the no of worker nodes in actual running cluster, ie. by changing the `worker.count` variable. That works perfectly fine for me.

Related to the actual description of the issue it is ok for drain to fail as we are anyways deleting the work node and full ocp setup along with bastion node.

**Comment by lukebrowning** [comment]
It is working now.
