### ISSUE TITLE
Delete bastion node after master and worker nodes

### ISSUE THREAD

**Issue by lukebrowning** [ocp-power-automation/ocp4-upi-powervs#225]
The bastion node is not automatically destroyed with the cluster.

**Comment by lukebrowning** [comment]
#223

**Comment by lukebrowning** [comment]
The bastion node serves no purpose after the master and worker nodes are deleted.   It should be removed automatically or perhaps by a terraform apply with the bastion count field set to 0.

**Comment by yussufsh** [comment]
Please describe the issue in detail. Which branch are you using and OCP version?
Did you do any manual changes via UI? Did you change the code any way?
What is created by TF will be deleted by TF during `terraform destroy` as per the terraform.state file information.

**Comment by lukebrowning** [comment]
It is working now
