### ISSUE TITLE
Wildcard DNS search in resolv.conf prevents resolving service IPs

### ISSUE THREAD

**Issue by jaywcarman** [ocp-power-automation/ocp4-upi-powervs#228]
I provisioned a cluster using `cluster_name = "nip.io"`, as suggested by the [var.tfvars comment](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/var.tfvars#L41).

When attempting to deploy an operator using an internal registry we ran into the following DNS issue (credit to @dberg1 for writing this up):

The `multicluster-operators-standalone-subscription` pod is trying to resolve IP address for hostname `multiclusterhub-repo.open-cluster-management.svc.cluster.local`.
Here is the `resolv.conf` of the pod:
```
# oc rsh -n open-cluster-management multicluster-operators-standalone-subscription-7d7986f9f6-rnpvj
sh-4.4$ cat /etc/resolv.conf
search open-cluster-management.svc.cluster.local svc.cluster.local cluster.local ocp-dal12-hub.169.59.253.69.nip.io 169.59.253.69.nip.io
nameserver 172.30.0.10
options ndots:5
```

Since the hostname the pod is trying to resolve has less than 5 dots, it will not do a direct lookup first.
It will try all the suffixes listed in the `search` list. Since `169.59.253.69.nip.io` is in the search list, it will always get the IP address of the bastion node (because [nip.io](https://nip.io/) is a wildcard DNS that will reply for any hostname under `169.59.253.69.nip.io`). `169.59.253.69.nip.io` should not be put in the `search` list.

**Comment by jaywcarman** [comment]
Additional note: I provisioned from the `release-4.7` branch (at c98d7d6)

**Comment by bpradipt** [comment]
@jaywcarman thanks for reporting this. We encountered this issue when working with cloud pak for data as well.
We will need to document this as a limitation.

**Comment by yussufsh** [comment]
These entries are added to the dhcp via helpernode. We should not have those configurations incase of wildcard domains.

@Prajyot-Parab can you work on helpernode repo to not use the `domain-search` [here](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/templates/dhcpd.conf.j2#L11) when wildcard domain is used?

**Comment by ssinha20** [comment]
@Prajyot-Parab / @yussufsh- Any further update on this issue?

**Comment by yussufsh** [comment]
This is fixed.
