### ISSUE TITLE
Make RHEL ethtool settings persistent across reboot at NAT gateway

### ISSUE THREAD

**Issue by ssinha20** [ocp-power-automation/ocp4-upi-powervs#311]
**Description:**
Make RHEL ethtool settings persistent by running: `nmcli con mod <NIC> ethtool.feature-rx off` for the public and private interface at NAT gateway(bastion).

**Ref-**
https://github.com/ocp-power-automation/ocp4-upi-powervs/issues/310

**cc,**
@Prajyot-Parab @cs-zhang @aishwaryabk @bpradipt

**Comment by yussufsh** [comment]
We can use #310 for fixing this issue.
