### ISSUE TITLE
Use vscsi attachment for volumes

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervs#316]

**Comment by bpradipt** [comment]
Early code to add support for vscsi in Terraform provider is available here -  - https://github.com/yussufsh/terraform-provider-ibm/tree/vscsi

**Comment by ssinha20** [comment]
Anybody willing to work on this issue?

**Comment by mkumatag** [comment]
This is not needed anymore, we have enough storage capacity available now.

cc @clnperez
