### ISSUE TITLE
Add support for P10

### ISSUE THREAD

**Issue by manojnkumar** [ocp-power-automation/ocp4-upi-powervs#358]
Add options to deploy to 1080/1022 systems.

**Comment by cs-zhang** [comment]
The system_type is already defined in vars.tf, so just set system_type to value 1080 or 1022, the OCP installation will be for P10.

**Comment by yussufsh** [comment]
This is not allowed yet via Terraform provider for IBM Cloud. The changes are in and will be published at the end of February. @cs-zhang to use it you need to upgrade the provider version in this project.

**Comment by yussufsh** [comment]
The provider version in this project is updated now. It allows p10 systems which needs to be passed with the variable `system_type` with one of the supported Machine type `s922/e880/e980/e1080/s1022`.
```
system_type         = "s1022"
```
