### ISSUE TITLE
The OCP installation failed on run `ocp4-helpernode` for CentOS-stream

### ISSUE THREAD

**Issue by cs-zhang** [ocp-power-automation/ocp4-upi-powervs#376]
For CentOS stream, the ansible playbook only installed core, that missing two required modules: openssh_keypair and firewalld.

**Comment by yussufsh** [comment]
So sticking with ansible 9 will solve the issues? 
Or we will need to fix the playbooks in helpernode and ocp4-playbooks

**Comment by cs-zhang** [comment]
We just need to fix it in our side TF code, no changes needed for ocp4-helpernode or ocp4-playbooks.

**Comment by cs-zhang** [comment]
The fix is merged, https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/377
