### ISSUE TITLE
Use 4.11 RHCOS image from the http or respective regions for the image import

### ISSUE THREAD

**Issue by mkumatag** [ocp-power-automation/ocp4-upi-powervs#386]
Now RHCOS images are published via RHCOS pipeline, so we need to use them instead of convert/import from qcow2

ref: https://github.com/openshift/installer/blob/046469ced964f4a70722a77ca271ea6d948998e7/data/data/coreos/rhcos.json#L247:L304

**Comment by mkumatag** [comment]
cc @clnperez @cs-zhang

**Comment by cs-zhang** [comment]
We just need to update `docs/ocp_prereqs_powervs.md` to point the RHCOS `.ova` location, so it can be directly downloaded, no convert steps required. Is that right, @mkumatag ?

**Comment by mkumatag** [comment]
> We just need to update `docs/ocp_prereqs_powervs.md` to point the RHCOS `.ova` location, so it can be directly downloaded, no convert steps required. Is that right, @mkumatag ?

yes, you are right.. the steps like convert, upload not required. We can directly import from the bucket now.

**Comment by mkumatag** [comment]
> Following details should be provided by the user through var.tfvars
> import_image - true/false (default=false). If this is true, image will be imported from cloud oject storage to PVS and below parameters should be provided by user.
> bucket_region
> bucket_name
> bucket_access - public/private (default=public). If this is private, access_key and secret_key should be provided.
> image_filename
> image_access_key
> image_secret_key
> image_storage_pool - tier1/tier3 (default=tier1)

What are these variables? do we have these somewhere already defined and handled?

**Comment by sajauddin** [comment]
These are the parameters needed by terraform provider to create an image from .owa.gz file available in Cloud Object storage.
So user has to provide these details and respective changes needs to be implemented. We do not have these variables readily available in this repo.

**Comment by mkumatag** [comment]
> These are the parameters needed by terraform provider to create an image from .owa.gz file available in Cloud Object storage.
> So user has to provide these details and respective changes needs to be implemented. We do not have these variables readily available in this repo.

I see, we need to explore a way to get this added into the current flow, also possible to this information from the release image itself.

**Comment by sajauddin** [comment]
There is an issue opened regarding the import of COS images from publicly accessible buckets. 
PowerVS issue: https://jsw.ibm.com/browse/POWERIAAS-5698

Due to this, facing issue while downloading image from object storage through terraform provider.

**Comment by sajauddin** [comment]
Fixed with PR https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/412
