### ISSUE TITLE
Race condition with bastion ignition file creation causing CoreOS nodes to fail to ignite

### ISSUE THREAD

**Issue by christopher-horn** [ocp-power-automation/ocp4-upi-powervs#388]
We have seen a deployment failure scenario where some of the CoreOS nodes fail to ignite properly.  We are running our automation using parallelism=3

The sequence of events appears to be as follows:

The first set of three nodes are created.  They boot. They grab their injected metadata from the virtual optical media.  They start polling the bastion for their ignition configs.  NetworkManager brings up dhcp and they obtain a lease from the bastion.  They poll for the ignition config, but _it is not ready yet_ so they get a 404. 

This is seen in the logs as follows:
```
[root@cecc-252966-bastion-0 httpd]# cat access_log
172.21.131.103 - - [09/Mar/2022:23:42:49 +0000] "GET /ignition/worker.ign HTTP/1.1" 404 196 "-" "Ignition/2.9.0"
172.21.131.229 - - [09/Mar/2022:23:42:50 +0000] "GET /ignition/bootstrap.ign HTTP/1.1" 404 196 "-" "Ignition/2.9.0"
172.21.131.98 - - [09/Mar/2022:23:42:56 +0000] "GET /ignition/master.ign HTTP/1.1" 404 196 "-" "Ignition/2.9.0"
```
Note the timestamps.  Here are the ignition files:
```
[root@cecc-252966-bastion-0 httpd]# ls -l /var/www/html/ignition/
total 276
-rw-r--r--. 1 root root 273952 Mar  9 23:44 bootstrap.ign
-rw-r--r--. 1 root root   1728 Mar  9 23:44 master.ign
-rw-r--r--. 1 root root   1728 Mar  9 23:44 worker.ign
```
Here is the specific creation time for the bootstrap.ign in this example:
```
[root@cecc-252966-bastion-0 httpd]# stat /var/www/html/ignition/bootstrap.ign 
  File: /var/www/html/ignition/bootstrap.ign
  Size: 273952    	Blocks: 536        IO Block: 65536  regular file
Device: fd03h/64771d	Inode: 71307151    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:httpd_sys_content_t:s0
Access: 2022-03-11 13:24:58.612327300 +0000
Modify: 2022-03-09 23:44:43.795413271 +0000
Change: 2022-03-09 23:44:44.105403678 +0000
 Birth: 2022-03-09 23:44:43.785413580 +0000
```
It seems once Ignition gets a 404 from the bastion, it stops trying to poll the bastion.  It continues to try to poll the OpenStack metadata endpoint at  http://169.254.169.254/openstack/latest/user_data for 5 minutes.  After 5 minutes the CoreOS node reboots.

At this point the virtual optical media with the metadata has already been removed from the CoreOS node though.  So it no longer reads in the ignition stub injected in the user_data and no longer knows it needs to fetch an ignition config from the bastion node.  It does obtain a DHCP lease but sits trying to poll the OpenStack metadata endpoint forever at that point.

**Comment by christopher-horn** [comment]
With the ability to create the network port objects, should this automation be taking the safer approach that the ocp4-upi-powervm takes by creating them first, then setting up helpernode, then creating the vms and doing the install? Is the missing piece needed to do this a ibm_pi_network_port data source?

**Comment by yussufsh** [comment]
Unfortunately we cannot use PowerVS network ports the way it works on OpenStack/PowerVC. There is no way to provide network port to a pvm instance. This feature was added by the team for special purpose such as database VIP, etc.

I have not seen this issue for quite some time, but was prominent during initial project days with PowerVS. After adding the httpTotal timeout  to the ignition this was gone. See https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/81/files for reference. After 500seconds if ignition is not successful then the node would reboot itself and try the dhcp, ignition step again.

More info will be needed if this is not a similar issue.

**Comment by christopher-horn** [comment]
Never mind.  I see that won't work.  With the port created ahead of time when one tries to create the VM it will complain the address is already in use.

**Comment by christopher-horn** [comment]
A solution to this problem is to deploy Redhat or CentOS on all the desired VM's.  Then the needed networking information is known and the bastion can be prepared for a network install of the nodes, the bootlist changed on the nodes to perform a network boot, and then the nodes rebooted and then reinstalled with CoreOS.

**Comment by christopher-horn** [comment]
Yes I revisited this and your explanation of the timeout mechanism here because of the 4.12 issue. Our automation is designed to call the Terraform pattern so we would need changes to use your wrapper script.

Approach you took shutting them down and restarting once bastion configured makes sense.

I am wondering if the network install approach would be cleaner in long run. Provision RHEL on them, set bootlist on them to the network adapter, and once bastion prepared reboot them to network install them.

Do you know if anyone opened issue with Redhat team about the timeout no longer working the same?

**Comment by yussufsh** [comment]
> Yes I revisited this and your explanation of the timeout mechanism here because of the 4.12 issue. Our automation is designed to call the Terraform pattern so we would need changes to use your wrapper script.
> 
Give me some time, I am in the process of making changes to the Terraform automation to stop the nodes as soon as they are provisioned and start them at a later stage when helpernode run is complete. I pointed to the script because I did not know about you using the code as a module.
Good to know that you were aware of the install script and I promote using the script for deploying OCP for common users who don't want to understand Terraform behaviour.

> Approach you took shutting them down and restarting once bastion configured makes sense.
> 
> I am wondering if the network install approach would be cleaner in long run. Provision RHEL on them, set bootlist on them to the network adapter, and once bastion prepared reboot them to network install them.
> 
This workaround seems to me complex to work with Terraform flow and will add many loc.

> Do you know if anyone opened issue with Redhat team about the timeout no longer working the same?

Please look at https://issues.redhat.com/browse/OCPBUGS-399 for reference.

**Comment by christopher-horn** [comment]
> I pointed to the script because I did not know about you using the code as a module.

We have a wrapper around it to manage it with ability to run a post apply script which we use to destroy the bootstrap once the provision is completed so as to not tie up the extra resources. We tweak the base pattern a little to not validate number of master nodes as we primarily deploy single node clusters as they are primarily short lived for education and demos. At the moment we have 37 deployed clusters and a number we're having problems with this week because of some kind of nova scheduling issue in lon06 and tor01. 

> This workaround seems to me complex to work with Terraform flow and will add many loc.

Agree, and your approach sounds just as good.

Thanks for the issue reference, good to understand why they removed it.

**Comment by yussufsh** [comment]
> ability to run a post apply script which we use to destroy the bootstrap once the provision is completed so as to not tie up the extra resources.

The [openshift-install-power](https://github.com/ocp-power-automation/openshift-install-power) does exactly that.

I am sure SNC should also be possible, though I have personally not tried it recently.

**Comment by christopher-horn** [comment]
Thinking about your approach more. You power off the nodes, but what happens if things take too long between then and time bastion is done being prepared and the virtual optical media with the injected ignition stub is unmapped and deleted by the VIOS before you power them back on?

**Comment by yussufsh** [comment]
> Thinking about your approach more. You power off the nodes, but what happens if things take too long between then and time bastion is done being prepared and the virtual optical media with the injected ignition stub is unmapped and deleted by the VIOS before you power them back on?

I am hoping that the ignition process has not started itself before I turn it off. When I start them in sequence, it should pick up the hosted ignition data.

**Comment by yussufsh** [comment]
@christopher-horn I have raised #460 with the above discussed changes.

I could deploy multiple ocp 4.12 clusters myself. Would like your help to validate as well from your side.

**Comment by christopher-horn** [comment]
Awesome, thanks!  I will test later this morning or afternoon once we are caught up on operational issues from the weekend.

**Comment by christopher-horn** [comment]
@yussufsh did you test with compact cluster with 3 masters or just normal 5 node deploy?

**Comment by christopher-horn** [comment]
@yussufsh with 3 masters and 0 workers:
```module.install.null_resource.bootstrap_complete (remote-exec): PLAY RECAP *********************************************************************
module.install.null_resource.bootstrap_complete (remote-exec): master-0                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.bootstrap_complete (remote-exec): master-1                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.bootstrap_complete (remote-exec): master-2                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.bootstrap_complete (remote-exec): tz-1426-bastion-0          : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

module.install.null_resource.bootstrap_complete: Creation complete after 16m1s [id=7661406827084073846]

Error: remote-exec provisioner error

  with module.install.null_resource.install,
  on modules/5_install/install.tf line 485, in resource "null_resource" "install":
 485:   provisioner "remote-exec" {
```

**Comment by christopher-horn** [comment]
Opened #461 to fix the above.

**Comment by yussufsh** [comment]
> @yussufsh did you test with compact cluster with 3 masters or just normal 5 node deploy?
> 
Sorry I did not try the compact cluster for you. Thanks for testing and the contributing to the code.

> Also I notice the coreos nodes only start to build after the bastion setup is fully complete, but they should be able to build in parallel as soon as the ip addresses for the bastion are known.
> 
This is to ensure bastion setup does not fail before we go to deploy additional hosts.

> Also if doing that and in the yum install for the bastion you add the other packages that the helpernode playbooks would install I think you can shave a little more time off.
IMO does not matter helpernode will be quicker in that case.

**Comment by christopher-horn** [comment]
Closing this as your recent changes should prevent it.
