### ISSUE TITLE
Automate Setting Node Labels

### ISSUE THREAD

**Issue by aishwaryabk** [ocp-power-automation/ocp4-upi-powervs#418]
As per the discussion on slack (https://ibm-systems-power.slack.com/archives/CLB0VTQF5/p1652797047535559):

There are some well-known k8s labels that the RHACM UI uses ([failure-domain.beta.kubernetes.io/region](http://failure-domain.beta.kubernetes.io/region), [failure-domain.beta.kubernetes.io/zone](http://failure-domain.beta.kubernetes.io/zone), and [beta.kubernetes.io/instance-type](http://beta.kubernetes.io/instance-type)) that could be set using values from the Terraform var.tfvars file.

According to the docs:
https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion

Ref:
https://ibm-systems-power.slack.com/archives/C01JKQWLK7X/p1652794487832839

**Comment by aishwaryabk** [comment]
Raised PR: https://github.com/ocp-power-automation/ocp4-playbooks/pull/163

**Comment by yussufsh** [comment]
@aishwaryabk Node labels should be a map variable so that user can add more labels in future without much or no code changes. I see in the PR you have hardcoded the labels.

**Comment by aishwaryabk** [comment]
@yussufsh Should we automate the 3 labels (zone, region & instance-type) and then add more custom labels via `nodes_labels` ?
