### ISSUE TITLE
Documentation Suggestion to alert folks to git pull terraform apply

### ISSUE THREAD

**Issue by prb112** [ocp-power-automation/ocp4-upi-powervs#434]
Working with a colleague, I ran into an out-of-date branch on the person's system. This lead to repeated deployment failures. A small Suggestion to add a warning to pull latest before executing a `terraform apply`.

**Comment by yussufsh** [comment]
IMO this should be a practice to check the latest code when user is facing some issue with existing code. Usually a user will run a `terraform apply` command where adding a message on top of the run is not possible.
We can add this statement to the doc or try other ways by using GitHub providers which can be tedious.
Also I want to mention folks to use https://github.com/ocp-power-automation/openshift-install-power/ instead where there is version check for the script and a single command would get the latest automation code.

If you have any other ideas then a PR is welcome.

**Comment by prb112** [comment]
While a best practice, I think it's fine to leave as-is.
