### ISSUE TITLE
Update hashicorp null and random providers to enable darwin/arm64 support

### ISSUE THREAD

**Issue by prb112** [ocp-power-automation/ocp4-upi-powervs#451]
# Background 
On darwin/arm64, I cloned and executed a `terraform init`. I encountered the following.

> ╷
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/hashicorp/random v2.3.1 does not have a package
> │ available for your current platform, darwin_arm64.
> │ 
> │ Provider releases are separate from Terraform CLI releases, so not all providers are
> │ available for all platforms. Other versions of this provider may have different
> │ platforms supported.
> ╵
> 
> ╷
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/hashicorp/null v2.1.2 does not have a package available
> │ for your current platform, darwin_arm64.
> │ 
> │ Provider releases are separate from Terraform CLI releases, so not all providers are
> │ available for all platforms. Other versions of this provider may have different
> │ platforms supported.
> ╵

Terraform added support for darwin/arm64. I updated hashicorp null and random providers locally, and it worked.

A composite of the version updates I had to make to pickup darwin/arm64. 

```
terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
  required_version = ">= 1.2.0"
}
```

If you'd like a PR raised, please let me know.

**Comment by yussufsh** [comment]
Thanks for creating the issue.

Yes we need to upgrade the providers. Even ignition provider started releasing arm64 payload. We also need to bump up IBM Cloud provider which has some fixes related to power APIs.

**Comment by prb112** [comment]
Hey Yussuf, great, I created a PR, however I wasn't able to get a successful deployment on MON01 - 
I did also set environment variables in openshift-install-power to point to the Branch I created, and it mostly worked until I had some reboot problems in powervs

**Comment by yussufsh** [comment]
@prb112 it is okay to raise that PR for random and null provider. Ignore the infrastructure issues. I will test out IBM Cloud provider changes later.
