### ISSUE TITLE
Using non-exist storage pool during openshift deploy

### ISSUE THREAD

**Issue by chenpingxy1** [ocp-power-automation/ocp4-upi-powervs#520]
1.**Describe in detail the issue you're having.**

With PowerVS, I used command "ibmcloud pi img cr"  command to copy the catalog image CentOS-stream-8 into my work space. After the local image was created the storage group value is empty (show as "ANY" in GUI). When I try to follow the https://github.com/ocp-power-automation/ocp4-upi-powervs playbook to deploy a cluster. I received a  storage pool "Tier3-Flash-1" not found error. Looks like the catalog image's storage pool is "Tier3-Flush-1". But we don't have that storage pool. To work around , I have to change the terraform file ocp4-upi-powervs/modules/1_prepare/prepare.tf to hard code an existing storage pool.

2.**What did you expect to happen? What happened instead? What would you like to see changed?**

User should have a way to specify the storage pool name in the  var.tfvars file

3.**What browser are you working in?**

Any

Steps to reproduce the issue

1.**Step one**

Setup a PowerVS env, without a storage pool named "Tier3-Flush-1"

2.**Step two**

Using ibmcloud pi img cr command to copy catalog image CentOS-stream-8 into your work space and make sure the storage pool is "ANY"

3.**Step three**

Follow the playbook https://github.com/ocp-power-automation/ocp4-upi-powervs to deploy a cluster. You will get the Tier3-Flush-1 storage pool not found error

**Comment by clnperez** [comment]
Hey @chenpingxy1 . Thanks for reporting. This one should be a pretty simple add, so could you take a stab at a PR?

**Comment by yussufsh** [comment]
I have also reported this to the PowerVS team and tagged @clnperez in the Slack thread.

**Comment by clnperez** [comment]
@chenpingxy1 ?

**Comment by chenpingxy1** [comment]
@yussufsh I will try to test it. Where I can get the latest code with the change and do you have a sample to specify the storage pool in the vars file. Thanks
