### ISSUE TITLE
Processing error: failure to load user cloud init data : cloud init data is of unsupported type or compressed

### ISSUE THREAD

**Issue by christopher-horn** [ocp-power-automation/ocp4-upi-powervs#527]
@yussufsh we started to receive the following error trying to provision Openshift clusters today:

Error: failed to provision: failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:create pvm-instance itzpvs-216365-bootstrap for cloud-instance 2d46a52c1b9f4a27a670cd5a6773e093 processing error: failure to load user cloud init data : cloud init data is of unsupported type or compressed Error:bad request Message:}

  with module.nodes.ibm_pi_instance.bootstrap[0],
  on modules/4_nodes/nodes.tf line 77, in resource "ibm_pi_instance" "bootstrap":
  77: resource "ibm_pi_instance" "bootstrap" {

Error: failed to provision: failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:create pvm-instance itzpvs-216365-master-0 for cloud-instance 2d46a52c1b9f4a27a670cd5a6773e093 processing error: failure to load user cloud init data : cloud init data is of unsupported type or compressed Error:bad request Message:}

  with module.nodes.ibm_pi_instance.master[0],
  on modules/4_nodes/nodes.tf line 130, in resource "ibm_pi_instance" "master":
 130: resource "ibm_pi_instance" "master" {

If I had to guess it looks like the PowerVS team probably updated the API this week and is now trying to validate the cloud init payload and thus rejecting an ignition payload.

I'm having some difficulty getting a support case open at the moment but will open one as soon as I can.

**Comment by yussufsh** [comment]
Is there any update on this? I had a user create a new worker node today using this automation without such an error.

**Comment by christopher-horn** [comment]
Oh, sorry, yes they fixed this in their deploy the following week and it has been okay since. Forgot I opened this here. Closing now.
