### ISSUE TITLE
Failed to connect to the host via ssh: ssh: connect to host eu-de-2-worker-0 port 22: No route to host

### ISSUE THREAD

**Issue by sckehan** [ocp-power-automation/ocp4-upi-powervs#529]
One worker node can not connect via ssh, and it is not ready in the cluster.

we try to shutdown and reboot the worker node, it is no useful.

I can not login to the worker node, so can not get more logs from the OS system.

What can I do to fix this issue.

**Comment by yussufsh** [comment]
This is fixed by re-adding the worker node and re-running the helpernode and install playbooks.
