### ISSUE TITLE
rh subscription failure should fail the installation

### ISSUE THREAD

**Issue by clnperez** [ocp-power-automation/ocp4-upi-powervs#75]
Currently if the subscription-manager subscribe step fails, the automation continues. Since no packages are installed, the bastion setup will not complete, which prevents the cluster installation. I see that the subscription manager registration is done via a series of shell commands inside an `inline` block. From what I've read, this will only fail if the very last command fails. I've experimented with dropping a `set -e` into the top of the inline section, but that still did not seem to cause the registration failure to halt the automation.

**Comment by bpradipt** [comment]
Good point.  We'll need to figure out how to fail fast in this case

**Comment by bpradipt** [comment]
Looks like one of the option is to use `script` - https://www.terraform.io/docs/provisioners/remote-exec.html ?

**Comment by yussufsh** [comment]
Thanks @clnperez for trying. You are right about last command failure.
Could you also try heredoc style for inline command to test [this way](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/modules/1_prepare/prepare.tf#L150). If this work for you please raise a PR.

**Comment by clnperez** [comment]
@yussufsh the heredoc style is already present in that `inline` block. @bpradipt it looks like it's a pain to get args into a script (https://www.terraform.io/docs/provisioners/remote-exec.html#script-arguments). Submitted a PR that seems to work after some testing.

**Comment by yussufsh** [comment]
You just have to add the `set -e` if it was already heredoc.

**Comment by clnperez** [comment]
I tried that, as stated in the summary:

>  I've experimented with dropping a set -e into the top of the inline section, but that still did not seem to cause the registration failure to halt the automation.

It still didn't fail.

**Comment by yussufsh** [comment]
It worked for `mkdir` atleast when I tried. Can you list your test cases here. I will give it a try tomorrow.

**Comment by yussufsh** [comment]
Closing this as per https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/99#issuecomment-734307821
