### ISSUE TITLE
Set http fetch timeout for ignition hosted on HTTP sever

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/ocp4-upi-powervs#76]
Ignition fetch stage continue to GET the HTTP file with default timeout set to 0 (indefinite).

Need to set the time to proper value in the automation.

Note: Ignition provider does not allow to change the timeout. Need to use string manipulation to add timeout in rendered ignition string.

**Comment by bpradipt** [comment]
Fixed by https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/81
